// app/frontend/components/index.svelte
<script lang="ts">
import { onMount } from "svelte";

let { path, viewData: data } = $props<{ path: string, viewData?: string }>()

const viewDataMap = $derived(JSON.parse(data ?? '{}'))
const viewData = $derived(viewDataMap && Object.keys(viewDataMap).length !== 0 ? viewDataMap : null)

let AsyncComponent: any = $state(null);

onMount(async () => {
  AsyncComponent = (await import(/* @vite-ignore */`./${path}.svelte`)).default
})
</script>

{#if AsyncComponent }
  <AsyncComponent viewData={viewData} />
{:else}
  <div>Loading...</div>
{/if}

// app/frontend/components/index.vue
<script lang="ts" setup>
import { defineAsyncComponent } from 'vue'

const { path, viewData: data } = defineProps<{ path: string; viewData?: string }>()

const viewDataMap = JSON.parse(data ?? '{}')
const viewData = viewDataMap && Object.keys(viewDataMap).length !== 0 ? viewDataMap : null

const AsyncComponent = defineAsyncComponent(() => import(/* @vite-ignore */ `./${path}.vue`))
</script>

<template>
  <Suspense>
    <AsyncComponent v-bind="viewData && { viewData }" />
    <template #fallback>
      <div>Loading...</div>
    </template>
  </Suspense>
</template>
